name: Cypress Tests

on:
  push

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: node -v
      - name: 'Cypress Tests - Chrome'
        uses: cypress-io/github-action@v5 # use the explicit version number
        with:
          # install: false # we have already installed all dependencies above
          start: npm run start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 1200
          browser: chrome
          # record: true
          # parallel: true
          # group: 'UI - Chrome'
          run: |
            cypress/integration/Homepage.feature --env configFile=cypress/config/cypress.json --reporter cypress-multi-reporters --reporter-options configFile=reporter-config.json
          # config-file: Cinema-FE/cypress-config.ts

      - name: Upload report to JIRA
        uses: automationwizards/jira-create-issue
        with:
          issue-key: RT-4296
          report-type: cypress
          report-file: ./mochawesome-report/mochawesome.json
          report-name: Cypress Test Report
