name: Cypress Tests

on:
  push

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: node -v
      - name: 'Cypress Tests - Chrome'
        uses: cypress-io/github-action@v5 # use the explicit version number
        with:
          # install: false # we have already installed all dependencies above
          start: npm run start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 1200
          browser: chrome
          # record: true
          # parallel: true
          # group: 'UI - Chrome'
          # run: npm cypress open
          spec: 'cypress/integration/Homepage.feature'
      # - name: Merge Mochawesome reports
      #   run: npx mochawesome-merge cypress/reports/mochawesome/*.json > cypress/reports/mochawesome/report.json
      - name: Generate Mochawesome HTML report
        run: npx marge cypress/reports/mochawesome/report.json -o cypress/reports/mochawesome
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: |
            cypress/videos/*.mp4
            cypress/screenshots/*.png
            cypress/reports/junit/*.xml
            cypress/reports/mochawesome/*.html
            cypress/reports/mochawesome/*.js
            cypress/reports/mochawesome/*.css

