name: Cypress Tests with Install Job and UI Chrome Job x 5

on: [push]

jobs:
  install:
  # ...

  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.0-chrome87-ff82
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: 'Cypress Tests - Chrome'
        uses: cypress-io/github-action@v5.x.x # use the explicit version number
        with:
          # we have already installed all dependencies above
          install: false
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
          spec: cypress/e2e/*